# Generated by Django 5.0.7 on 2024-08-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagina_Home',
            new_name='GerenciarCategoria',
        ),
        migrations.RenameModel(
            old_name='Comentario',
            new_name='GerenciarComentario',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='GerenciarPagina_Home',
        ),
        migrations.RenameModel(
            old_name='Pagina_Inicial',
            new_name='GerenciarPagina_Inicial',
        ),
        migrations.RenameModel(
            old_name='Produto',
            new_name='GerenciarProduto',
        ),
        migrations.RenameModel(
            old_name='Receita',
            new_name='GerenciarReceita',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='GerenciarUsuario',
        ),
        migrations.RenameModel(
            old_name='Vivencia',
            new_name='GerenciarVivencia',
        ),
        migrations.AlterModelOptions(
            name='gerenciarcategoria',
            options={'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarpagina_home',
            options={'verbose_name_plural': 'Pagina_Home'},
        ),
        migrations.RenameField(
            model_name='gerenciarcategoria',
            old_name='nome_alergia',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='gerenciarpagina_home',
            old_name='nome',
            new_name='nome_alergia',
        ),
    ]
