# Generated by Django 5.0.7 on 2024-08-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pagina_home_gerenciarcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciarproduto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciarcategoria'),
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciarcategoria'),
        ),
    ]
